local function error_record(id, severity, exit_class, retryable, summary, next_action)
  return {
    id = id,
    severity = severity,
    exit_class = exit_class,
    retryable = retryable,
    summary = summary,
    next_action = next_action,
  }
end

local function check(id, stage, required, online, dependencies, owner)
  return {
    id = id,
    stage = stage,
    required = required,
    online = online,
    dependencies = dependencies or {},
    owner = owner,
  }
end

return {
  contract_version = "0.1.0-readiness.1",
  decision_refs = { "D-022", "D-055", "D-062" },
  severities = { "info", "warning", "error", "fatal" },
  exit_classes = {
    success = 0,
    general_error = 1,
    usage = 2,
    invalid_config = 3,
    lock_conflict = 4,
    interaction_required = 5,
    resolver_negative = 6,
    cancelled = 7,
  },

  errors = {
    error_record("UsageError", "error", "usage", false, "Invalid command usage.", "Run --help for the canonical grammar."),
    error_record("ConfigMissing", "error", "invalid_config", false, "The main configuration is missing.", "Run --config-repl or --model-repl."),
    error_record("ConfigInvalid", "error", "invalid_config", false, "The candidate configuration is invalid.", "Open the reported field in --config-repl."),
    error_record("ConfigChanged", "error", "invalid_config", true, "The configuration changed during publication.", "Reload, review, and retry the transaction."),
    error_record("ModelUnavailable", "error", "invalid_config", true, "The selected Model is unavailable.", "Select or repair an enabled Model."),
    error_record("PermissionUnavailable", "error", "invalid_config", false, "The selected Permission is unavailable.", "Map the Context to a valid Permission."),
    error_record("TtyRequired", "error", "interaction_required", false, "This action requires an interactive terminal.", "Use a complete non-interactive projection where supported."),
    error_record("OnlineConsentRequired", "error", "interaction_required", false, "Online self-test consent is required.", "Add the explicit invocation consent or use Stage 1."),
    error_record("NotFound", "error", "resolver_negative", true, "No matching Context was found.", "Refresh the Catalog or use a precise hash."),
    error_record("HashCollision", "error", "resolver_negative", false, "The Context hash matches multiple paths.", "Choose a displayed logical path explicitly."),
    error_record("MatchedUnavailable", "error", "resolver_negative", true, "A matching Context is unavailable.", "Inspect permissions or repair the Context."),
    error_record("ScanIncomplete", "warning", "resolver_negative", true, "The Context scan is incomplete.", "Review the unread scope before concluding absence."),
    error_record("ScanLimit", "warning", "resolver_negative", true, "The Context scan reached its hard limit.", "Narrow the view or repair the Catalog layout."),
    error_record("TargetChanged", "error", "general_error", true, "The selected target changed after inspection.", "Refresh and confirm the new target snapshot."),
    error_record("OpenConflict", "error", "general_error", true, "The Context cannot be opened in its observed state.", "Refresh or use context-repl self-fix."),
    error_record("DestinationExists", "error", "general_error", false, "The destination already exists.", "Choose another name or root; no overwrite occurred."),
    error_record("LockConflict", "error", "lock_conflict", true, "The Context has an active writer.", "Wait for the writer or use evidence-based self-fix."),
    error_record("UnsupportedPath", "error", "general_error", false, "The path cannot be represented losslessly.", "Choose a supported real path."),
    error_record("UnsupportedObject", "error", "general_error", false, "The target object kind is unsupported.", "Use a regular file or directory as required."),
    error_record("PathEscapesWorkspace", "error", "general_error", false, "The target resolves outside the workspace.", "Use an in-root target or satisfy OutsideWorkspace policy."),
    error_record("PermissionDenied", "error", "general_error", false, "Permission policy denied the operation.", "Choose a permitted operation or change configuration explicitly."),
    error_record("ApprovalRequired", "warning", "interaction_required", true, "Human approval is required.", "Review the bound operation snapshot."),
    error_record("ApprovalStale", "warning", "interaction_required", true, "The approved operation snapshot is stale.", "Review and approve the new snapshot."),
    error_record("ToolSchemaInvalid", "error", "general_error", false, "Tool arguments failed schema validation.", "Correct the tool call; it was not executed."),
    error_record("ToolFailed", "error", "general_error", true, "The tool returned an error.", "Inspect the bounded result and retry only if safe."),
    error_record("ToolCancelled", "warning", "cancelled", true, "The tool was cancelled.", "Inspect the paired result before continuing."),
    error_record("ToolUnknown", "fatal", "general_error", false, "The tool side effect cannot be proven.", "Resolve the unknown operation before continuing."),
    error_record("ProcessTimeout", "error", "general_error", true, "The process exceeded its deadline.", "Inspect termination evidence before retrying."),
    error_record("NetworkError", "error", "general_error", true, "The Model transport failed.", "Inspect endpoint, proxy, CA, and retry state."),
    error_record("ProtocolError", "error", "general_error", false, "The Model response violated the adapter protocol.", "Run Model self-test and inspect recorded diagnostics."),
    error_record("StorageError", "fatal", "general_error", true, "Durable storage publication failed.", "Stop side effects and use context-repl self-fix."),
    error_record("ContextCorrupt", "fatal", "general_error", false, "The Context failed structural or relation validation.", "Open it read-only and use context-repl self-fix."),
    error_record("ContextVersionUnsupported", "error", "general_error", false, "The Context schema version is unsupported.", "Use a compatible yaca or an explicit migration."),
    error_record("ContextHardLimit", "fatal", "general_error", false, "The Context reached its hard resource limit.", "Export it and start a new Context with a handoff prompt."),
    error_record("ContextStale", "fatal", "general_error", true, "The active Context target changed externally.", "Stop, refresh, and explicitly recover or rebind."),
    error_record("BudgetExhausted", "error", "general_error", false, "A runtime hard budget was exhausted.", "Review the partial facts and start a bounded follow-up."),
    error_record("Stuck", "error", "general_error", false, "The no-progress detector stopped the turn.", "Review the durable warning and choose the next action."),
    error_record("Cancelled", "warning", "cancelled", true, "The action was cancelled.", "Inspect the final typed outcome."),
    error_record("InternalError", "fatal", "general_error", false, "An internal invariant failed.", "Preserve the Context and report the stable error details."),
  },

  self_test = {
    stages = { 1, 2, 3 },
    strict_dependency_order = true,
    stage1_online_requests = false,
    stage2_consent = "visible-tty-or-explicit-current-invocation",
    stage3_is_advisory = true,
    required_exclusion_result = "partial",
    startup_gate_accepts_partial = false,
    checks = {
      check("ST1-PLATFORM", 1, true, false, {}, "platform"),
      check("ST1-PACKAGE", 1, true, false, { "ST1-PLATFORM" }, "release"),
      check("ST1-SAFE-LOAD", 1, true, false, { "ST1-PLATFORM", "ST1-PACKAGE" }, "runtime"),
      check("ST1-DATA-ROOT", 1, true, false, { "ST1-PLATFORM" }, "platform"),
      check("ST1-CONFIG-SCHEMA", 1, true, false, { "ST1-PACKAGE" }, "config"),
      check("ST1-CONFIG-SOURCE", 1, true, false, { "ST1-CONFIG-SCHEMA", "ST1-DATA-ROOT" }, "config"),
      check("ST1-ATOMIC-WRITE", 1, true, false, { "ST1-DATA-ROOT" }, "platform"),
      check("ST1-CONTEXT-CODEC", 1, true, false, { "ST1-PLATFORM" }, "context"),
      check("ST1-CONTEXT-SCHEMA", 1, true, false, { "ST1-CONTEXT-CODEC" }, "context"),
      check("ST1-CONTEXT-CATALOG", 1, true, false, { "ST1-DATA-ROOT", "ST1-CONTEXT-CODEC" }, "context"),
      check("ST1-CONTEXT-LOCK", 1, true, false, { "ST1-CONTEXT-CATALOG" }, "context"),
      check("ST1-TOOLS", 1, true, false, { "ST1-SAFE-LOAD" }, "tools"),
      check("ST1-CA-BUNDLE", 1, true, false, { "ST1-PACKAGE" }, "network"),
      check("ST1-TTY-INPUT", 1, false, false, { "ST1-PLATFORM" }, "tui"),
      check("ST1-ZERO-SURFACE", 1, true, false, { "ST1-PACKAGE", "ST1-CONFIG-SCHEMA" }, "release"),

      check("ST2-MODEL-TRANSPORT", 2, true, true, { "ST1-CA-BUNDLE", "ST1-CONFIG-SOURCE" }, "model"),
      check("ST2-MODEL-AUTH", 2, true, true, { "ST2-MODEL-TRANSPORT" }, "model"),
      check("ST2-MODEL-WIRE", 2, true, true, { "ST2-MODEL-AUTH" }, "model"),
      check("ST2-MODEL-STREAM", 2, true, true, { "ST2-MODEL-WIRE" }, "model"),
      check("ST2-MODEL-TOOLS", 2, true, true, { "ST2-MODEL-WIRE", "ST1-TOOLS" }, "model"),
      check("ST2-MODEL-CONTROL", 2, true, true, { "ST2-MODEL-TOOLS" }, "model"),
      check("ST2-MODEL-USAGE-CANCEL", 2, true, true, { "ST2-MODEL-STREAM" }, "model"),

      check("ST3-CONFIG-SEMANTICS", 3, false, true, { "ST2-MODEL-CONTROL" }, "diagnostics"),
      check("ST3-PERMISSION-SEMANTICS", 3, false, true, { "ST2-MODEL-CONTROL" }, "diagnostics"),
      check("ST3-NAMING-AND-SPELLING", 3, false, true, { "ST2-MODEL-CONTROL" }, "diagnostics"),
    },
  },

  persistence = {
    standalone_log_file = false,
    standalone_diagnostic_xml = false,
    background_spool = false,
    context_durable_diagnostics = "only-when-context-is-healthy-and-event-is-required",
    pre_context_or_stale_fatal = "stderr-and-exit-code",
    explicit_self_test_report = "stdout",
  },
}
