local function gate(id, status, artifact, proof, task, hard_gate)
  return {
    id = id,
    status = status,
    artifact = artifact,
    proof = proof,
    implementation_task = task,
    hard_gate = hard_gate,
  }
end

local function task(id, milestone, depends, files, tests, commit)
  return {
    id = id,
    milestone = milestone,
    depends = depends,
    files = files,
    tests = tests,
    commit = commit,
  }
end

return {
  contract_version = "0.1.0-readiness.1",
  readiness_version = "yaca-coding-readiness-2026-08-29.1",
  decision_refs = { "D-002", "D-007", "D-009", "D-056", "D-057", "D-069", "D-070", "D-071" },

  gates = {
    A = {
      name = "implementation-plan-ready",
      status = "passed",
      meaning = "all-current-product-semantics-have-one-machine-contract-or-bounded-plan-task-and-every-pending-proof-has-a-hard-gate-and-failure-path",
      audit = ".develope-docs/GATE-AUDIT-2026-08-29.md",
    },
    B = {
      name = "coding-ready",
      status = "passed",
      meaning = "whole-program-files-dependencies-tests-exit-criteria-and-commit-boundaries-are-frozen",
      plan = ".develope-docs/IMPLEMENTATION-PLAN.md",
      first_task = "C01",
    },
    R = {
      name = "qualification-and-release",
      status = "closed",
      meaning = "implementation-complete-and-independent-win32-win64-linux-target-evidence-required",
      release_authorized = false,
      pending_targets = { "win32-x86", "win64-x86_64", "linux-x86_64" },
      required_proof_status = "proven-target",
    },
  },

  source_start = {
    authorized_after_this_contract_and_validators_commit = true,
    implementation_phase = "implemented-unqualified",
    allowed_implementation_phases = { "pre-coding", "implementing", "implemented-unqualified" },
    source_is_currently_skeleton_only = false,
    release_is_not_authorized = true,
    first_task = "C01",
    transitions = {
      { from = "pre-coding", to = "implementing", task = "C02" },
      { from = "implementing", to = "implemented-unqualified", task = "C30" },
    },
    public_status_markers = {
      ["pre-coding"] = { en = "not implemented yet", zh = "目前尚未实现", plan = "尚未开始产品实现" },
      implementing = { en = "implementation in progress", zh = "正在实现", plan = "产品实现进行中" },
      ["implemented-unqualified"] = { en = "implementation complete; target qualification pending", zh = "实现已完成；目标资格验证待完成", plan = "产品实现已完成 / 资格验证待完成" },
    },
  },

  gate_a_items = {
    gate("AR-P0-01", "qualification-bound", "product.lua+zero_surface.lua+release.lua", "final-journey-and-zip-scan-pending", "C33", "before-release"),
    gate("AR-P0-02", "plan-ready", "runtime.lua+model.lua+agentloop-fixtures", "synthetic-traces-pass;target-fault-traces-scheduled", "C26", "before-M8-complete"),
    gate("AR-P0-03", "qualification-bound", "model.lua+wire-fixtures", "synthetic-exact-bytes;TP-015-recorded-pending", "C21", "before-M6-complete"),
    gate("AR-P0-04", "qualification-bound", "platform.lua+transport.lua", "TP-003-proven-modern;TP-004/005-target-pending", "C04", "before-target-adapters-complete"),
    gate("AR-P0-05", "qualification-bound", "tui.lua+tui-transcripts", "40-column-synthetic-pass;target-terminal-transcripts-pending", "C14", "before-M4-complete"),
    gate("AR-P0-06", "qualification-bound", "tools.lua+transport.lua+permission-fixtures", "permission-fold-pass;target-process/path-pending", "C25", "before-M7-complete"),
    gate("AR-P0-07", "qualification-bound", "tools.lua+context.lua+subsystems/19", "TP-008-proven-modern;target-fault-matrix-pending", "C25", "before-M7-complete"),
    gate("AR-P0-08", "qualification-bound", "formats.lua+transport.lua+DATA-CLASSIFICATION.md", "TP-006-scanner-proven-modern;target-carrier-pending", "C19", "before-M6-complete"),
    gate("AR-P0-09", "qualification-bound", "config.lua+formats.lua+config-fixtures", "grammar-synthetic-pass;target-atomic-write-and-caps-pending", "C10", "before-M3-complete"),
    gate("AR-P0-10", "qualification-bound", "context.lua+context.rng+formats.lua", "TP-008/010-proven-modern;target-filesystem/performance-pending", "C17", "before-M5-complete"),
    gate("AR-P0-11", "qualification-bound", "context.lua+formats.lua+path-fixtures", "SHA-256-vectors-pass;target-path-identity-pending", "C16", "before-M5-complete"),
    gate("AR-P0-12", "plan-ready", "runtime.lua+context.lua+subsystems/12", "threshold-and-long-session-test-scheduled", "C28", "before-M8-complete"),
    gate("AR-P0-13", "qualification-bound", "actions.lua+argv-fixtures+tui-transcripts", "synthetic-parser/machine-contract-pass;target-argv/TTY-pending", "C12", "before-M4-complete"),
    gate("AR-P0-14", "qualification-bound", "platform.lua+release.lua+zero_surface.lua", "allowlists-frozen;TP-029-target-pending", "C04", "before-M10-complete"),
    gate("AR-P0-15", "qualification-bound", "platform.lua+context.lua+transport.lua", "TP-008-process-crash-modern;target-lock/kill-pending", "C17", "before-M5-complete"),
    gate("AR-P0-16", "qualification-bound", "product.lua+release.lua+IMPLEMENTATION-PLAN.md", "luainstaller-1.3.0-modern;three-target-qualification-pending", "C32", "before-release"),

    gate("AR-P1-01", "qualification-bound", "formats.lua+format-fixtures", "TP-010-proven-modern;three-ABI-load-pending", "C08", "before-M10-complete"),
    gate("AR-P1-02", "qualification-bound", "transport.lua+transport-fixtures", "TP-006-proven-modern;target-TLS/proxy/CA-pending", "C19", "before-M6-complete"),
    gate("AR-P1-03", "qualification-bound", "transport.lua+platform.lua", "shell-carrier-frozen;target-process-tree-pending", "C25", "before-M7-complete"),
    gate("AR-P1-04", "plan-ready", "runtime.lua+release.lua", "hard-cap-dimensions-frozen;calibration-task-scheduled", "C26", "before-M8-complete"),
    gate("AR-P1-05", "plan-ready", "prompts.lua+prompt-fixtures", "exact-prompt-and-layer-crosswalk-pass", "C22", "before-M6-complete"),
    gate("AR-P1-06", "qualification-bound", "context.lua+release.lua", "no-archive-policy-frozen;target-size/latency-pending", "C18", "before-M5-complete"),
    gate("AR-P1-07", "plan-ready", "diagnostics.lua+actions.lua", "stable-error/check-registry-pass", "C30", "before-M9-complete"),
    gate("AR-P1-08", "qualification-bound", "release.lua+TECHNICAL-PROOF-BACKLOG.md", "dimensions-and-fixtures-defined;target-calibration-pending", "C32", "before-release"),
    gate("AR-P1-09", "plan-ready", "release.lua+formats.lua+all-machine-contracts", "stable-names-and-candidate-manifest-frozen", "C01", "before-each-consuming-milestone"),
    gate("AR-P1-10", "plan-ready", "context.rng+context.lua+formats.lua", "internal-reference-reader-and-export-tests-scheduled", "C15", "before-M5-complete"),
    gate("AR-P1-11", "qualification-bound", "release.lua+proof-manifest", "source-pins-frozen;curl/CA/target-SBOM-pending", "C31", "before-release"),
    gate("AR-P1-12", "plan-ready", "README.md+README-zh.md+CURRENT-STATE.md", "not-implemented-boundary-scan-pass", "C34", "before-release"),
  },

  milestones = {
    { id = "M0", name = "harness-and-manifest", tasks = { "C01" } },
    { id = "M1", name = "platform-and-event-core", tasks = { "C02", "C03", "C04" } },
    { id = "M2", name = "formats-and-path", tasks = { "C05", "C06", "C07", "C08", "C09" } },
    { id = "M3", name = "configuration-and-bootstrap", tasks = { "C10", "C11" } },
    { id = "M4", name = "actions-cli-and-tui", tasks = { "C12", "C13", "C14" } },
    { id = "M5", name = "context-storage-and-index", tasks = { "C15", "C16", "C17", "C18" } },
    { id = "M6", name = "network-model-and-prompts", tasks = { "C19", "C20", "C21", "C22" } },
    { id = "M7", name = "tools-permission-and-change", tasks = { "C23", "C24", "C25" } },
    { id = "M8", name = "agentloop-and-compaction", tasks = { "C26", "C27", "C28" } },
    { id = "M9", name = "diagnostics-and-self-test", tasks = { "C29", "C30" } },
    { id = "M10", name = "packaging-and-qualification", tasks = { "C31", "C32", "C33", "C34" } },
  },

  tasks = {
    task("C01", "M0", {}, { "test/run.lua", "test/support/assert.lua", "release/manifest.lua", ".tools/check_loader.lua" }, { "test/self/harness_test.lua", "test/self/manifest_test.lua" }, "test: establish harness and release manifest"),
    task("C02", "M1", { "C01" }, { "src/platform.lua", "test/support/fake_native.lua", ".develope-docs/contracts/readiness.lua", ".develope-docs/IMPLEMENTATION-PLAN.md", ".develope-docs/subsystems/01-platform-abstraction.md", "README.md", "README-zh.md" }, { "test/unit/platform_test.lua" }, "feat: add validated platform identity port"),
    task("C03", "M1", { "C02" }, { "src/runtime.lua", "src/clock.lua" }, { "test/unit/event_pump_test.lua" }, "feat: add deterministic runtime event pump"),
    task("C04", "M1", { "C03" }, { "src/backend_linux.lua", "src/backend_windows.lua", "src/fs.lua", "src/process.lua", "src/terminal.lua", "native/yaca_native.c" }, { "test/integration/native_ports_test.lua", "test/qualification/loader_path_test.lua" }, "feat: add narrow native platform adapters"),
    task("C05", "M2", { "C01" }, { "src/text.lua" }, { "test/unit/text_test.lua" }, "feat: add strict utf8 and byte carriers"),
    task("C06", "M2", { "C05" }, { "src/json.lua" }, { "test/unit/json_test.lua" }, "feat: add strict canonical json codec"),
    task("C07", "M2", { "C05" }, { "src/ini.lua" }, { "test/unit/ini_test.lua" }, "feat: add strict ini parser and writer"),
    task("C08", "M2", { "C05", "C06" }, { "src/xml.lua", "native/lxp_build.lua" }, { "test/unit/xml_test.lua", "test/integration/lxp_corpus_test.lua" }, "feat: add bounded xml codec"),
    task("C09", "M2", { "C02", "C05" }, { "src/path.lua" }, { "test/unit/path_test.lua" }, "feat: add logical path and context hash codec"),
    task("C10", "M3", { "C06", "C07", "C09" }, { "src/config.lua", "src/safety.lua" }, { "test/unit/config_test.lua", "test/integration/config_generation_test.lua" }, "feat: add typed configuration generations"),
    task("C11", "M3", { "C03", "C10" }, { "src/session.lua", "src/main.lua" }, { "test/integration/bootstrap_test.lua" }, "feat: add offline bootstrap lifecycle"),
    task("C12", "M4", { "C10", "C11" }, { "src/cli.lua" }, { "test/unit/cli_parser_test.lua", "test/golden/help" }, "feat: generate cli from semantic actions"),
    task("C13", "M4", { "C05", "C12" }, { "src/tui.lua" }, { "test/golden/tui", "test/unit/tui_renderer_test.lua" }, "feat: add deterministic transcript renderer"),
    task("C14", "M4", { "C04", "C13" }, { "src/terminal.lua", "src/tui.lua" }, { "test/integration/line_editor_test.lua", "test/qualification/terminal_transcript_test.lua" }, "feat: add draft-safe terminal editor"),
    task("C15", "M5", { "C08", "C10" }, { "src/context.lua" }, { "test/unit/context_schema_test.lua", "test/reference/context_reader_test.lua" }, "feat: add canonical context document model"),
    task("C16", "M5", { "C09", "C15" }, { "src/index.lua", "src/path.lua" }, { "test/unit/index_test.lua", "test/golden/resolver" }, "feat: add deterministic context resolver"),
    task("C17", "M5", { "C04", "C15" }, { "src/context.lua", "src/fs.lua" }, { "test/fault/context_commit_test.lua", "test/integration/context_lock_test.lua" }, "feat: add recoverable context publication"),
    task("C18", "M5", { "C16", "C17" }, { "src/context.lua", "src/index.lua" }, { "test/fault/context_management_test.lua" }, "feat: add context lifecycle transactions"),
    task("C19", "M6", { "C03", "C04", "C06", "C10" }, { "src/network.lua", "src/process.lua" }, { "test/integration/curl_carrier_test.lua", "test/qualification/network_target_test.lua" }, "feat: add secret-safe curl transport"),
    task("C20", "M6", { "C05", "C06", "C19" }, { "src/network.lua" }, { "test/unit/sse_test.lua", "test/fault/network_retry_test.lua" }, "feat: add bounded sse and retry controller"),
    task("C21", "M6", { "C20" }, { "src/model.lua" }, { "test/golden/provider_wire", "test/integration/model_adapter_test.lua" }, "feat: add canonical model adapters"),
    task("C22", "M6", { "C10", "C21" }, { "src/prompt.lua", "src/model.lua" }, { "test/golden/prompts", "test/unit/control_mapping_test.lua" }, "feat: add versioned prompt and control bundles"),
    task("C23", "M7", { "C10", "C15" }, { "src/permission.lua", "src/safety.lua" }, { "test/unit/permission_test.lua" }, "feat: add permission admission service"),
    task("C24", "M7", { "C04", "C09", "C23" }, { "src/tools.lua", "src/fs.lua" }, { "test/integration/direct_tools_test.lua", "test/fault/target_reverify_test.lua" }, "feat: add verified direct tools"),
    task("C25", "M7", { "C17", "C19", "C23", "C24" }, { "src/tools.lua", "src/process.lua", "src/context.lua" }, { "test/integration/exec_tool_test.lua", "test/fault/operation_outcome_test.lua" }, "feat: add raw exec and durable operations"),
    task("C26", "M8", { "C03", "C18", "C22", "C25" }, { "src/runtime.lua" }, { "test/golden/agentloop", "test/fault/agentloop_test.lua" }, "feat: connect typed agent loop"),
    task("C27", "M8", { "C26" }, { "src/runtime.lua", "src/session.lua" }, { "test/integration/review_queue_side_test.lua" }, "feat: add reviews queue and side turns"),
    task("C28", "M8", { "C15", "C21", "C26" }, { "src/compact.lua" }, { "test/unit/compact_test.lua", "test/performance/long_context_test.lua" }, "feat: add lossless model-view compaction"),
    task("C29", "M9", { "C11", "C26" }, { "src/diagnostics.lua" }, { "test/unit/diagnostics_test.lua", "test/golden/errors" }, "feat: add stable diagnostics projection"),
    task("C30", "M9", { "C18", "C21", "C25", "C29" }, { "src/diagnostics.lua", "src/main.lua", ".develope-docs/contracts/readiness.lua", ".develope-docs/IMPLEMENTATION-PLAN.md", "README.md", "README-zh.md" }, { "test/integration/self_test_test.lua" }, "feat: add staged self-test runner"),
    task("C31", "M10", { "C30" }, { "release/manifest.lua", "release/luainstaller.lua", "release/dependencies.lock" }, { "test/release/package_layout_test.lua", "test/release/sbom_test.lua" }, "build: assemble minimal target packages"),
    task("C32", "M10", { "C31" }, { "test/qualification/win32.lua", "test/qualification/win64.lua", "test/qualification/linux.lua" }, { "test/qualification" }, "test: qualify all release targets"),
    task("C33", "M10", { "C32" }, { ".tools/check_zero_surface.lua", "test/release/journeys.lua" }, { "test/release/clean_machine_test.lua", "test/release/journeys.lua" }, "test: prove release journeys and zero surface"),
    task("C34", "M10", { "C33" }, { "README.md", "README-zh.md", "docs", "release/evidence" }, { ".tools/check_documentation_truth.lua" }, "docs: publish qualified release evidence"),
  },
}
