local states = {
  "Idle",
  "Preparing",
  "RequestingModel",
  "Streaming",
  "DispatchingTools",
  "AwaitingApproval",
  "ExecutingTool",
  "EvaluatingAction",
  "EvaluatingTermination",
  "WaitingUser",
  "Finalizing",
  "Closing",
}
local outcomes = {
  "completed",
  "waiting_user",
  "refused",
  "cancelled",
  "budget_exhausted",
  "stuck",
  "partial",
  "error",
  "unknown_side_effect",
}

return {
  contract_version = "0.1.0-readiness.1",
  decision_refs = { "D-020", "D-033", "D-051", "D-066", "D-067", "AL06-50=A" },

  identities = {
    "Process",
    "ActiveContext",
    "Turn",
    "LogicalRequest",
    "Attempt",
    "ToolCall",
    "Operation",
    "QueueItem",
    "ConfigGeneration",
  },
  states = states,
  outcomes = outcomes,

  controls = {
    {
      id = "finish",
      required_payload = {},
      optional_payload = { "summary" },
      state_when_doublecheck = "EvaluatingTermination",
      state_without_doublecheck = "Finalizing",
      proposed_outcome = "completed",
    },
    {
      id = "ask-user",
      required_payload = { "question" },
      optional_payload = {},
      next_state = "WaitingUser",
      reported_outcome = "waiting_user",
    },
    {
      id = "refuse",
      required_payload = { "reason" },
      optional_payload = {},
      next_state = "Finalizing",
      proposed_outcome = "refused",
    },
  },

  transitions = {
    { from = "Idle", to = "Preparing", on = "main-input-durable" },
    { from = "Idle", to = "Closing", on = "quit" },
    { from = "Preparing", to = "RequestingModel", on = "view-ready" },
    { from = "Preparing", to = "Finalizing", on = "admission-error-or-cancel" },
    { from = "Preparing", to = "Closing", on = "close" },
    { from = "RequestingModel", to = "Streaming", on = "first-canonical-provider-event" },
    { from = "RequestingModel", to = "Finalizing", on = "terminal-error-or-cancel" },
    { from = "RequestingModel", to = "Closing", on = "close" },
    { from = "Streaming", to = "DispatchingTools", on = "complete-valid-tool-batch" },
    { from = "Streaming", to = "WaitingUser", on = "ask-user-or-model-yield" },
    { from = "Streaming", to = "EvaluatingTermination", on = "finish-doublecheck-on" },
    { from = "Streaming", to = "Finalizing", on = "finish-doublecheck-off-or-refuse-or-terminal-error" },
    { from = "Streaming", to = "Closing", on = "close" },
    { from = "DispatchingTools", to = "EvaluatingAction", on = "high-risk-review" },
    { from = "DispatchingTools", to = "AwaitingApproval", on = "permission-confirm" },
    { from = "DispatchingTools", to = "ExecutingTool", on = "admitted" },
    { from = "DispatchingTools", to = "RequestingModel", on = "batch-results-durable" },
    { from = "DispatchingTools", to = "Finalizing", on = "terminal-error-or-cancel" },
    { from = "DispatchingTools", to = "Closing", on = "close" },
    { from = "EvaluatingAction", to = "AwaitingApproval", on = "review-pass-and-confirm" },
    { from = "EvaluatingAction", to = "ExecutingTool", on = "review-pass-and-allow" },
    { from = "EvaluatingAction", to = "DispatchingTools", on = "review-deny-synthetic-result" },
    { from = "EvaluatingAction", to = "WaitingUser", on = "review-uncertain" },
    { from = "EvaluatingAction", to = "Finalizing", on = "terminal-error-or-cancel" },
    { from = "EvaluatingAction", to = "Closing", on = "close" },
    { from = "AwaitingApproval", to = "ExecutingTool", on = "approved" },
    { from = "AwaitingApproval", to = "DispatchingTools", on = "rejected-synthetic-result" },
    { from = "AwaitingApproval", to = "WaitingUser", on = "approval-deferred" },
    { from = "AwaitingApproval", to = "Finalizing", on = "terminal-error-or-cancel" },
    { from = "AwaitingApproval", to = "Closing", on = "close" },
    { from = "ExecutingTool", to = "DispatchingTools", on = "result-durable-more-tools" },
    { from = "ExecutingTool", to = "RequestingModel", on = "result-durable-batch-complete" },
    { from = "ExecutingTool", to = "Finalizing", on = "terminal-error-cancel-or-unknown" },
    { from = "ExecutingTool", to = "Closing", on = "close" },
    { from = "EvaluatingTermination", to = "Finalizing", on = "review-pass" },
    { from = "EvaluatingTermination", to = "RequestingModel", on = "explicit-gap" },
    { from = "EvaluatingTermination", to = "WaitingUser", on = "uncertain-error-or-cap" },
    { from = "EvaluatingTermination", to = "Closing", on = "close" },
    { from = "WaitingUser", to = "Preparing", on = "reply-requires-readmission-work" },
    { from = "WaitingUser", to = "RequestingModel", on = "reply-durable" },
    { from = "WaitingUser", to = "Finalizing", on = "cancel-or-terminal-error" },
    { from = "WaitingUser", to = "Closing", on = "close" },
    { from = "Finalizing", to = "Idle", on = "outcome-durable" },
    { from = "Finalizing", to = "Closing", on = "close-after-outcome" },
  },

  invariants = {
    mutable_domain_threads = 1,
    active_contexts_max = 1,
    active_main_turns_max = 1,
    inflight_side_requests_max = 1,
    concurrent_tools_max = 1,
    accepted_tool_call_results = "exactly-one-real-or-synthetic",
    provider_stop_means_completed = false,
    natural_language_done_means_finish = false,
    queue_auto_start_outcome = "completed",
    queue_auto_start_requires_no_pending_or_unknown = true,
  },

  hard_caps = {
    source = "versioned-release-manifest",
    proof_required = { "TP-017", "TP-022" },
    dimensions = {
      "process-wall-time",
      "turn-wall-time",
      "logical-model-requests",
      "transport-attempts",
      "tool-calls",
      "reviews",
      "retries",
      "input-tokens-or-bytes",
      "output-tokens-or-bytes",
      "event-queue-depth",
      "process-output-bytes",
      "context-bytes",
    },
    unlimited_sentinel = false,
    user_may_only_tighten = true,
  },

  stuck_detector = {
    source = "versioned-release-manifest",
    proof_required = { "TP-017", "TP-022" },
    detectors = { "exact-repeat", "same-error", "abab-cycle", "semantic-no-progress" },
    behavior = { "durable-warning", "one-bounded-escape-step", "stuck" },
    user_config_fields = {},
    context_override_fields = {},
  },
}
