return {
  contract_version = "0.1.0-readiness.1",
  decision_refs = { "D-039", "D-050", "D-052", "D-055", "D-056", "M05-55=A", "M05-58=A", "M05-59=A" },

  async_port_methods = { "start", "poll", "cancel", "join", "close" },
  terminal_outcomes = { "completed", "cancelled", "failed", "unknown" },

  process = {
    foreground_only = true,
    interactive = false,
    pty = false,
    tracked_background = false,
    detached = false,
    stdin = "closed-before-user-code-runs",
    stdout = "separate-bounded-byte-stream",
    stderr = "separate-bounded-byte-stream",
    shell = {
      windows = {
        executable = "native-GetSystemDirectoryW/cmd.exe",
        fixed_arguments = { "/d", "/s", "/c" },
        command = "one-opaque-UTF-16-command-preserving-canonical-UTF-8-source",
      },
      linux = {
        executable = "/bin/sh",
        fixed_arguments = { "-c" },
        command = "one-opaque-argv-element-preserving-canonical-bytes",
      },
    },
    environment = {
      default = "minimal",
      alternate = "inherit_filtered",
      values_are_never_durable = true,
      minimal_names = { "PATH", "SystemRoot", "TEMP", "TMP", "HOME", "LANG", "LC_ALL", "TERM" },
      always_remove_names = {
        "LUA_PATH", "LUA_CPATH", "LUA_INIT", "LUA_INIT_5_5",
        "CURL_HOME", "CURL_CA_BUNDLE", "SSL_CERT_FILE", "SSL_CERT_DIR", "NETRC",
      },
      registered_secret_values = "scan-before-publication-not-persisted",
    },
    result_required = {
      "outcome", "exit_kind", "exit_code", "signal_or_exception", "stdout",
      "stderr", "stdout_truncated", "stderr_truncated", "decoder", "duration_ms",
      "descendants_proven_stopped",
    },
    cancellation = "never-claim-cancelled-unless-process-tree-terminal-is-proven",
    proof_required = { "TP-003", "TP-005", "TP-029" },
  },

  curl = {
    executable = "absolute-bundled-component-path",
    fixed_argv = { "--disable", "--silent", "--show-error", "--no-buffer", "--config", "-" },
    first_option = "--disable",
    config_carrier = "anonymous-stdin-pipe",
    request_body_carrier = "0600-or-Windows-owner-only-create-new-temp",
    response_header_carrier = "owner-only-create-new-temp",
    secret_in_argv = false,
    secret_in_environment = false,
    curl_builtin_retry = 0,
    curl_automatic_redirect = false,
    protocol_allowlist = { "http", "https" },
    content_encoding = "identity-v0.1",
    ambient_environment = "allowlist-and-explicit-options-only",
    default_config = "disabled",
    netrc = "disabled",
    proxy = "only-Network-fields-current-request-snapshot",
    ca = "only-release-CA-or-explicit-CaBundlePath-current-request-snapshot",
    output = "stdout-only-response-body-SSE;stderr-diagnostic-captured-and-redacted",
    cleanup = "bounded-startup-recovery+request-finally",
  },

  http = {
    request_identity = { "logical_request_id", "attempt_id", "model_snapshot", "retry_snapshot" },
    method = "POST",
    redirect = {
      automatic_by_curl = false,
      statuses = { 307, 308 },
      maximum = "release-manifest",
      same_origin = "exact-lowercase-scheme+IDNA-host+effective-port",
      cross_origin = "reject-before-new-network-write",
      https_downgrade = "reject",
      new_attempt_id = true,
      key_reuse = "same-origin-only-after-policy-revalidation",
    },
    retry = {
      owner = "Runtime-not-curl",
      count_meaning = "automatic-attempts-after-first",
      snapshot = { "route", "count", "base_delay_ms", "exponent", "max_delay_ms", "jitter", "manifest_id" },
      eligible_before_canonical_event = { "dns", "connect", "tls-before-body", "http-429", "http-503" },
      never_eligible = { "auth-4xx", "ordinary-4xx", "protocol", "content-refusal", "cancel", "outcome-unknown" },
      retry_after = "minimum-wait-then-fail-if-any-budget-or-runtime-cap-would-be-exceeded",
      model_switch = false,
      active_config_reload = false,
      constants_source = "release-manifest",
    },
    explicit_http = "allowed-only-after-config-save/change-warning;never-implicit-downgrade",
  },

  secret_scanner = {
    registry_source = "typed-config-secret-registry",
    empty_value = "schema-error",
    below_minimum = "consumer-ineligible",
    duplicate_value = "one-pattern+stable-sorted-class/source-set",
    chunking = "max-pattern-bytes-minus-one-tail",
    overlapping_hits = "maximal-byte-interval-union",
    marker_contains = { "secret-class", "destination", "reason" },
    marker_forbids = { "raw-value", "actual-length", "equality-fingerprint" },
    constants_source = "release-manifest",
    proof_required = { "TP-006", "TP-010" },
  },

  forbidden = {
    "curlrc", "netrc", "ambient-proxy", "ambient-CA", "telemetry-request",
    "diagnostic-upload", "update-request", "direct-http-tool", "media-helper",
  },
}
